# Use postgres/example user/password credentials
# https://hub.docker.com/_/postgres
version: '3.1'
services:
  migracao_dados:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# docker compose up